### ISSUE TITLE
Multiple Breaking Errors after upgrading to latest Parse.

### ISSUE THREAD

**Issue by grosscorporation** [dplewis/parse-server-mysql-adapter#31]
`TypeError: Cannot read property '*' of undefined
    at SchemaData.get (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\SchemaController.js:549:84)
    at SchemaController.getClassLevelPermissions (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\SchemaController.js:1308:27)
    at SchemaController.validatePermission (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\SchemaController.js:1304:53)
    at validateClassName.then.then.schemaController (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\DatabaseController.js:796:63)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error: Uncaught internal server error.Cannot read property '*' of undefined {"stack":"TypeError: Cannot read property '*' of undefined\n    at SchemaData.get (C:\\apps\\rentoza-stories\\server\\node_modules\\parse-server\\lib\\Controllers\\SchemaController.js:549:84)\n    at SchemaController.getClassLevelPermissions (C:\\apps\\rentoza-stories\\server\\node_modules\\parse-server\\lib\\Controllers\\SchemaController.js:1308:27)\n    at SchemaController.validatePermission (C:\\apps\\rentoza-stories\\server\\node_modules\\parse-server\\lib\\Controllers\\SchemaController.js:1304:53)\n    at validateClassName.then.then.schemaController (C:\\apps\\rentoza-stories\\server\\node_modules\\parse-server\\lib\\Controllers\\DatabaseController.js:796:63)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
TypeError: Cannot read property '*' of undefined
    at SchemaData.get (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\SchemaController.js:549:84)
    at SchemaController.getClassLevelPermissions (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\SchemaController.js:1308:27)
    at SchemaController.validatePermission (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\SchemaController.js:1304:53)
    at validateClassName.then.then.schemaController (C:\apps\rentoza-stories\server\node_modules\parse-server\lib\Controllers\DatabaseController.js:796:63)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by nicky258irl** [comment]
@dplewis
